### ISSUE TITLE
Genome assembler Spades can not run properly!

### ISSUE THREAD

**Issue by hngyou** [kapsakcj/win10-linux-conda-how-to#1]
Hi,
I like to do some bioinformatics analysis on win10-Linux (Ubuntu 16.04). This How-to is very helpful to me. But, when I tried Spades, that didn't work very well. I installed it using anaconda, and the installation process is OK, and when I used $spades,py --help    , it would give the help information properly. But if I used $spades.py --test    , there will be an error. I have used my data to test it, but I never got Spades worked.
Have you tried Spades in you win10-Linux? Would you please give me some advices?
Yours,
Hngyou

**Comment by kapsakcj** [comment]
Hi Hngyou,

I'm glad the tutorial was helpful! Yes, I have been able to get spades to work fine on my windows 10 computer running Ubuntu. I can try to help you out.

What was the error message that you saw after running `spades.py --test` ?

**Comment by hngyou** [comment]
Hi kapsakcj,
Thank you for your reply.
I have found the resolution. Here is the link of the problem other people also had and with the resolution ( https://wpdev.uservoice.com/forums/266908-command-prompt-console-windows-subsystem-for-l/suggestions/13516878-please-make-the-spades-genome-assembler-compatible) 
 And Youtube also have a video for this resolution (https://www.youtube.com/watch?v=i-mRZ7VXRBA). I have tried the latest verion of Spades (3.12.0), and it works very well.
Thanks anyway.  :)
Hngyou

**Comment by kapsakcj** [comment]
No problem. I'm glad you got it running!

Curtis

**Comment by dhuelgas** [comment]
Hi! I have the same problem(can't run SPAdes using Ubuntu 18.04 subsystem on Windows 10) . I wanted to check the links that hngyou shared but they are not longer available. Neither the web page nor the Youtube video with the resolutions. :(
Can anybody help me, please?
